export enum UserStatusesEnum {
  I_AM_NEW_HERE = 'I_AM_NEW_HERE',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PERSONALITY_VERIFICATION = 'PERSONALITY_VERIFICATION',
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
}
